// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA_Gng2EukUX21FD6k9s4Lzw50Q8pW5rw',
    appId: '1:586922404130:android:6bae4955e5a31a40d3dd7b',
    messagingSenderId: '586922404130',
    projectId: 'helloworld-2b816',
    databaseURL: 'https://helloworld-2b816-default-rtdb.firebaseio.com',
    storageBucket: 'helloworld-2b816.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADUiO1Ez-uoRpza3X6cpsIUqK5Y7oqWOE',
    appId: '1:586922404130:ios:c0319ce11090184dd3dd7b',
    messagingSenderId: '586922404130',
    projectId: 'helloworld-2b816',
    databaseURL: 'https://helloworld-2b816-default-rtdb.firebaseio.com',
    storageBucket: 'helloworld-2b816.appspot.com',
    iosClientId: '586922404130-0nicfguo2lej0bdck9rebnk9e5gaaaii.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFlutterTest2',
  );

}